import { defineFlow } from '@genkit-ai/flow'
import { generate } from '@genkit-ai/ai'
import { googleAI } from '@genkit-ai/googleai'
import { initializeGenkit } from '../genkit'
import { DocumentRequestSchema, DocumentResponseSchema } from '../types/legal'
import { DEFAULT_MODEL } from '../../agents/types'

// Initialize Genkit
initializeGenkit()

export const runDocumentGenerator = defineFlow(
  {
    name: 'documentGenerator',
    inputSchema: DocumentRequestSchema,
    outputSchema: DocumentResponseSchema,
  },
  async (input) => {
    const response = await generate({
      model: DEFAULT_MODEL,
      prompt: `You are LegalEase AI, a legal document generation specialist for Indian business law.

Generate professional legal documents that are:
- Compliant with Indian laws and regulations
- Appropriate for the specified jurisdiction
- Written in clear, professional language
- Structured with proper sections and clauses
- Include necessary disclaimers and legal notices

Document Type: ${input.documentType}
Business: ${input.businessDetails.name}
Business Type: ${input.businessDetails.type}
Jurisdiction: ${input.businessDetails.jurisdiction}

Always include this disclaimer: "This document is generated by AI and should be reviewed by a qualified legal professional before use."

Generate a ${input.documentType} for ${input.businessDetails.name}, a ${input.businessDetails.type} business in ${input.businessDetails.jurisdiction}. ${input.customFields ? `Additional requirements: ${JSON.stringify(input.customFields)}` : ''}`,
      config: {
        temperature: 0.2,
        maxOutputTokens: 2000,
      },
    })

    const documentText = response.text()
    
    return {
      document: documentText,
      title: `${input.documentType.replace('-', ' ').toUpperCase()} - ${input.businessDetails.name}`,
      sections: [
        {
          heading: 'Document Body',
          content: documentText,
        },
      ],
      disclaimers: [
        'This document is generated by AI and should be reviewed by a qualified legal professional before use.',
        'Laws and regulations may vary by jurisdiction and change over time.',
        'This document does not constitute legal advice.',
      ],
    }
  }
)