import { definePrompt } from '@genkit-ai/ai'
import { z } from 'zod'

export const documentGenerationPrompt = definePrompt(
  {
    name: 'documentGeneration',
    inputSchema: z.object({
      documentType: z.string(),
      businessName: z.string(),
      businessType: z.string(),
      jurisdiction: z.string(),
      customFields: z.object({}).optional(),
    }),
  },
  async (input) => {
    return {
      messages: [
        {
          role: 'system',
          content: [
            {
              text: `You are LegalEase AI, a legal document generation specialist for Indian business law.

Generate professional legal documents that are:
- Compliant with Indian laws and regulations
- Appropriate for the specified jurisdiction
- Written in clear, professional language
- Structured with proper sections and clauses
- Include necessary disclaimers and legal notices

Document Type: ${input.documentType}
Business: ${input.businessName}
Business Type: ${input.businessType}
Jurisdiction: ${input.jurisdiction}

Always include this disclaimer: "This document is generated by AI and should be reviewed by a qualified legal professional before use."`,
            },
          ],
        },
        {
          role: 'user',
          content: [
            {
              text: `Generate a ${input.documentType} for ${input.businessName}, a ${input.businessType} business in ${input.jurisdiction}. ${input.customFields ? `Additional requirements: ${JSON.stringify(input.customFields)}` : ''}`,
            },
          ],
        },
      ],
    }
  }
)