import { NextRequest, NextResponse } from 'next/server'

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { documentType, businessDetails } = body

    if (!documentType || !businessDetails) {
      return NextResponse.json(
        { error: 'Document type and business details are required' },
        { status: 400 }
      )
    }

    // TODO: Replace with actual document generation
    const response = {
      result: {
        document: `Generated ${documentType} for ${businessDetails.name}`,
        title: `${documentType.toUpperCase()} - ${businessDetails.name}`,
        sections: [
          {
            heading: 'Document Content',
            content: 'Document generation is being set up. Please check back soon.'
          }
        ],
        disclaimers: [
          'This document is generated by AI and should be reviewed by a qualified legal professional.',
          'Laws may vary by jurisdiction and change over time.'
        ]
      }
    }

    return NextResponse.json(response)
  } catch (error) {
    console.error('Documents API error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}